time: 14400
nodes: 1
procs: 20
account string: default_project
queue: q24h
========================================================================
Will be using 20 threads
Cycle complete with 5 comps and size 5 took 9 ms
Cycle complete with 6 comps and size 37 took 30 ms
Cycle complete with 7 comps and size 280 took 32 ms
Cycle complete with 8 comps and size 1773 took 122 ms
Cycle complete with 9 comps and size 9333 took 776 ms
Cycle complete with 10 comps and size 41289 took 9096 ms
Cycle complete with 11 comps and size 148272 took 102539 ms
Cycle complete with 12 comps and size 400048 took 845006 ms
Cycle complete with 13 comps and size 728014 took 3567496 ms
Cycle complete with 14 comps and size 817276 took 6254572 ms
========================================================================
Epilogue args:
Date: Thu Mar  3 18:54:10 CET 2016
Allocated nodes:
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
r3i2n14
Job ID: 20260539.icts-p-svcs-1
User ID: vsc31468
Group ID: vsc31468
Job Name: test9_shortComp.pbs
Session ID: 48180
Resource List: neednodes=1:ppn=20,nodes=1:ppn=20,pmem=1gb,walltime=04:00:00
Resources Used: cput=73:20:22,mem=4433488kb,vmem=35984592kb,walltime=04:00:42
Queue Name: q24h
Account String: 
-------------------------------------------------------------------------
time: 14442
nodes: 1
procs: 20
account: default_project
