time: 300
nodes: 1
procs: 20
account string: default_project
queue: q1h
========================================================================
Will be using 20 threads
Cycle complete with 2 comps and size 2 took 6 ms
Cycle complete with 3 comps and size 1 took 1 ms
Took 91420945 ns
[3, 6, 3]
Will be using 20 threads
Cycle complete with 2 comps and size 3 took 3 ms
Cycle complete with 3 comps and size 4 took 1 ms
Cycle complete with 4 comps and size 2 took 1 ms
Cycle complete with 5 comps and size 1 took 0 ms
Took 16933678 ns
[3, 12, 5, 10, 6]
Will be using 20 threads
Cycle complete with 2 comps and size 3 took 3 ms
Cycle complete with 3 comps and size 6 took 1 ms
Cycle complete with 4 comps and size 11 took 2 ms
Cycle complete with 5 comps and size 10 took 2 ms
Cycle complete with 6 comps and size 7 took 2 ms
Cycle complete with 7 comps and size 6 took 1 ms
Cycle complete with 8 comps and size 4 took 1 ms
Cycle complete with 9 comps and size 1 took 1 ms
Took 25051018 ns
[3, 6, 3, 24, 10, 20, 12, 5, 3]
Will be using 20 threads
Cycle complete with 2 comps and size 3 took 3 ms
Cycle complete with 3 comps and size 7 took 3 ms
Cycle complete with 4 comps and size 17 took 4 ms
Cycle complete with 5 comps and size 36 took 10 ms
Cycle complete with 6 comps and size 53 took 36 ms
Cycle complete with 7 comps and size 53 took 5 ms
Cycle complete with 8 comps and size 44 took 4 ms
Cycle complete with 9 comps and size 23 took 1 ms
Cycle complete with 10 comps and size 8 took 1 ms
Cycle complete with 11 comps and size 4 took 1 ms
Cycle complete with 12 comps and size 1 took 1 ms
Took 82439151 ns
[3, 6, 3, 24, 48, 24, 9, 18, 10, 36, 12, 24]
Will be using 20 threads
Cycle complete with 2 comps and size 3 took 4 ms
Cycle complete with 3 comps and size 7 took 4 ms
Cycle complete with 4 comps and size 19 took 5 ms
Cycle complete with 5 comps and size 51 took 23 ms
Cycle complete with 6 comps and size 141 took 12 ms
Cycle complete with 7 comps and size 325 took 20 ms
Cycle complete with 8 comps and size 564 took 18 ms
Cycle complete with 9 comps and size 678 took 18 ms
Cycle complete with 10 comps and size 510 took 10 ms
Cycle complete with 11 comps and size 280 took 6 ms
Cycle complete with 12 comps and size 106 took 3 ms
Cycle complete with 13 comps and size 33 took 1 ms
Cycle complete with 14 comps and size 11 took 0 ms
Cycle complete with 15 comps and size 6 took 0 ms
Cycle complete with 16 comps and size 1 took 0 ms
Took 141477278 ns
[3, 6, 24, 96, 10, 72, 33, 3, 48, 24, 96, 10, 36, 20, 12, 96]
Will be using 20 threads
Cycle complete with 2 comps and size 3 took 3 ms
Cycle complete with 3 comps and size 7 took 3 ms
Cycle complete with 4 comps and size 20 took 7 ms
Cycle complete with 5 comps and size 57 took 31 ms
Cycle complete with 6 comps and size 189 took 20 ms
Cycle complete with 7 comps and size 648 took 39 ms
Cycle complete with 8 comps and size 2088 took 87 ms
Cycle complete with 9 comps and size 5701 took 295 ms
Cycle complete with 10 comps and size 11673 took 1110 ms
Cycle complete with 11 comps and size 16110 took 2084 ms
Cycle complete with 12 comps and size 13347 took 1968 ms
Cycle complete with 13 comps and size 6760 took 824 ms
Cycle complete with 14 comps and size 2268 took 164 ms
Cycle complete with 15 comps and size 528 took 15 ms
Cycle complete with 16 comps and size 81 took 3 ms
Cycle complete with 17 comps and size 24 took 1 ms
Cycle complete with 18 comps and size 8 took 0 ms
Cycle complete with 19 comps and size 1 took 0 ms
Took 6680307154 ns
[3, 12, 48, 192, 5, 10, 80, 160, 36, 66, 6, 96, 17, 20, 6, 136, 40, 24, 96]
========================================================================
Epilogue args:
Date: Thu Feb 25 11:53:22 CET 2016
Allocated nodes:
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
r4i0n14
Job ID: 20255097.icts-p-svcs-1
User ID: vsc31468
Group ID: vsc31468
Job Name: test2to8.pbs
Session ID: 53084
Resource List: neednodes=1:ppn=20,nodes=1:ppn=20,pmem=1gb,walltime=00:05:00
Resources Used: cput=00:00:00,mem=0kb,vmem=0kb,walltime=00:00:08
Queue Name: q1h
Account String: 
-------------------------------------------------------------------------
time: 8
nodes: 1
procs: 20
account: default_project
