time: 180
nodes: 1
procs: 20
account string: default_project
queue: q1h
========================================================================
Will be using 20 threads
Cycle complete with 2 comps and size 3 took 6 ms
Cycle complete with 3 comps and size 7 took 6 ms
Cycle complete with 4 comps and size 20 took 13 ms
Cycle complete with 5 comps and size 59 took 34 ms
Cycle complete with 6 comps and size 208 took 34 ms
Cycle complete with 7 comps and size 807 took 73 ms
Cycle complete with 8 comps and size 3415 took 214 ms
Cycle complete with 9 comps and size 14339 took 1535 ms
Cycle complete with 10 comps and size 55974 took 16668 ms
Cycle complete with 11 comps and size 188689 took 160606 ms
========================================================================
Epilogue args:
Date: Thu Feb 25 10:03:27 CET 2016
Allocated nodes:
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
r1i2n8
Job ID: 20255014.icts-p-svcs-1
User ID: vsc31468
Group ID: vsc31468
Job Name: test9_debugmode.pbs
Session ID: 29202
Resource List: neednodes=1:ppn=20,nodes=1:ppn=20,pmem=3gb,walltime=00:03:00
Resources Used: cput=00:55:31,mem=1091404kb,vmem=20551672kb,walltime=00:03:15
Queue Name: q1h
Account String: 
-------------------------------------------------------------------------
time: 195
nodes: 1
procs: 20
account: default_project
