time: 18000
nodes: 1
procs: 24
account string: default_project
queue: q24h
========================================================================
Will be using 48 threads
Cycle complete with 2 comps and size 3 took 7 ms
Cycle complete with 3 comps and size 4 took 1 ms
Cycle complete with 4 comps and size 2 took 1 ms
Cycle complete with 5 comps and size 1 took 1 ms
Took 113863597 ns
[3, 12, 5, 10, 6]
Will be using 48 threads
Cycle complete with 2 comps and size 3 took 3 ms
Cycle complete with 3 comps and size 6 took 1 ms
Cycle complete with 4 comps and size 11 took 1 ms
Cycle complete with 5 comps and size 10 took 2 ms
Cycle complete with 6 comps and size 7 took 2 ms
Cycle complete with 7 comps and size 6 took 1 ms
Cycle complete with 8 comps and size 4 took 1 ms
Cycle complete with 9 comps and size 1 took 1 ms
Took 25033323 ns
[3, 6, 3, 24, 10, 20, 12, 5, 3]
Will be using 48 threads
Cycle complete with 2 comps and size 3 took 3 ms
Cycle complete with 3 comps and size 7 took 2 ms
Cycle complete with 4 comps and size 17 took 4 ms
Cycle complete with 5 comps and size 36 took 8 ms
Cycle complete with 6 comps and size 53 took 16 ms
Cycle complete with 7 comps and size 53 took 11 ms
Cycle complete with 8 comps and size 44 took 6 ms
Cycle complete with 9 comps and size 23 took 2 ms
Cycle complete with 10 comps and size 8 took 1 ms
Cycle complete with 11 comps and size 4 took 0 ms
Cycle complete with 12 comps and size 1 took 1 ms
Took 68515076 ns
[3, 6, 3, 24, 48, 24, 9, 18, 10, 36, 12, 24]
Will be using 48 threads
Cycle complete with 2 comps and size 3 took 4 ms
Cycle complete with 3 comps and size 7 took 2 ms
Cycle complete with 4 comps and size 19 took 4 ms
Cycle complete with 5 comps and size 51 took 22 ms
Cycle complete with 6 comps and size 141 took 18 ms
Cycle complete with 7 comps and size 325 took 23 ms
Cycle complete with 8 comps and size 564 took 52 ms
Cycle complete with 9 comps and size 678 took 56 ms
Cycle complete with 10 comps and size 510 took 32 ms
Cycle complete with 11 comps and size 280 took 17 ms
Cycle complete with 12 comps and size 105 took 6 ms
Cycle complete with 13 comps and size 33 took 2 ms
Cycle complete with 14 comps and size 11 took 1 ms
Cycle complete with 15 comps and size 6 took 0 ms
Cycle complete with 16 comps and size 1 took 1 ms
Took 254523115 ns
[3, 6, 3, 24, 96, 40, 80, 48, 9, 18, 10, 80, 36, 12, 24, 96]
Will be using 48 threads
Cycle complete with 2 comps and size 3 took 4 ms
Cycle complete with 3 comps and size 7 took 3 ms
Cycle complete with 4 comps and size 20 took 11 ms
Cycle complete with 5 comps and size 57 took 44 ms
Cycle complete with 6 comps and size 189 took 21 ms
Cycle complete with 7 comps and size 648 took 72 ms
Cycle complete with 8 comps and size 2088 took 266 ms
Cycle complete with 9 comps and size 5703 took 625 ms
Cycle complete with 10 comps and size 11668 took 1470 ms
Cycle complete with 11 comps and size 16094 took 2821 ms
Cycle complete with 12 comps and size 13304 took 2758 ms
Cycle complete with 13 comps and size 6678 took 1066 ms
Cycle complete with 14 comps and size 2222 took 192 ms
Cycle complete with 15 comps and size 503 took 44 ms
Cycle complete with 16 comps and size 77 took 14 ms
Cycle complete with 17 comps and size 18 took 1 ms
Cycle complete with 18 comps and size 9 took 0 ms
Cycle complete with 19 comps and size 1 took 0 ms
Took 9434952472 ns
[3, 12, 48, 192, 5, 10, 6, 80, 160, 96, 17, 34, 18, 68, 136, 40, 96, 20, 24]
Will be using 48 threads
Cycle complete with 2 comps and size 3 took 9 ms
Cycle complete with 3 comps and size 7 took 6 ms
Cycle complete with 4 comps and size 20 took 12 ms
Cycle complete with 5 comps and size 59 took 20 ms
Cycle complete with 6 comps and size 208 took 32 ms
Cycle complete with 7 comps and size 807 took 173 ms
Cycle complete with 8 comps and size 3415 took 609 ms
Cycle complete with 9 comps and size 14343 took 2494 ms
Cycle complete with 10 comps and size 55976 took 27697 ms
Cycle complete with 11 comps and size 188687 took 238346 ms
Cycle complete with 12 comps and size 490224 took 1408245 ms
========================================================================
Epilogue args:
Date: Wed Apr 13 10:58:54 CEST 2016
Allocated nodes:
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
Job ID: 20281806.hpc-p-svcs-10.icts.hpc.kuleuven.be
User ID: vsc31468
Group ID: vsc31468
Job Name: test20160413_noTrim.pbs
Session ID: 9996
Resource List: neednodes=1:ppn=24:haswell,nodes=1:ppn=24:haswell,pmem=1gb,walltime=05:00:00
Resources Used: cput=10:37:19,energy_used=0,mem=5578336kb,vmem=23645776kb,walltime=00:28:28
Queue Name: q24h
Account String: 
-------------------------------------------------------------------------
time: 1708
nodes: 1
procs: 24
account: default_project
