time: 18000
nodes: 1
procs: 24
account string: default_project
queue: q24h
========================================================================
Will be using 24 threads
Cycle complete with 2 comps and size 3 took 6 ms
Cycle complete with 3 comps and size 4 took 1 ms
Cycle complete with 4 comps and size 2 took 1 ms
Cycle complete with 5 comps and size 1 took 1 ms
Took 109026077 ns
[3, 12, 5, 10, 6]
Will be using 24 threads
Cycle complete with 2 comps and size 3 took 2 ms
Cycle complete with 3 comps and size 6 took 1 ms
Cycle complete with 4 comps and size 11 took 1 ms
Cycle complete with 5 comps and size 10 took 2 ms
Cycle complete with 6 comps and size 7 took 2 ms
Cycle complete with 7 comps and size 6 took 1 ms
Cycle complete with 8 comps and size 4 took 1 ms
Cycle complete with 9 comps and size 1 took 1 ms
Took 25748741 ns
[3, 6, 3, 24, 10, 20, 12, 5, 3]
Will be using 24 threads
Cycle complete with 2 comps and size 3 took 3 ms
Cycle complete with 3 comps and size 7 took 2 ms
Cycle complete with 4 comps and size 17 took 4 ms
Cycle complete with 5 comps and size 36 took 8 ms
Cycle complete with 6 comps and size 53 took 16 ms
Cycle complete with 7 comps and size 53 took 12 ms
Cycle complete with 8 comps and size 44 took 5 ms
Cycle complete with 9 comps and size 23 took 2 ms
Cycle complete with 10 comps and size 8 took 0 ms
Cycle complete with 11 comps and size 4 took 0 ms
Cycle complete with 12 comps and size 1 took 1 ms
Took 66820104 ns
[3, 6, 3, 24, 48, 24, 9, 18, 10, 36, 12, 24]
Will be using 24 threads
Cycle complete with 2 comps and size 3 took 4 ms
Cycle complete with 3 comps and size 7 took 1 ms
Cycle complete with 4 comps and size 19 took 4 ms
Cycle complete with 5 comps and size 51 took 20 ms
Cycle complete with 6 comps and size 141 took 19 ms
Cycle complete with 7 comps and size 325 took 23 ms
Cycle complete with 8 comps and size 564 took 55 ms
Cycle complete with 9 comps and size 678 took 57 ms
Cycle complete with 10 comps and size 510 took 31 ms
Cycle complete with 11 comps and size 280 took 16 ms
Cycle complete with 12 comps and size 105 took 6 ms
Cycle complete with 13 comps and size 33 took 1 ms
Cycle complete with 14 comps and size 11 took 1 ms
Cycle complete with 15 comps and size 6 took 1 ms
Cycle complete with 16 comps and size 1 took 0 ms
Took 254444729 ns
[3, 6, 3, 24, 96, 40, 80, 48, 9, 18, 10, 80, 36, 12, 24, 96]
Will be using 24 threads
Cycle complete with 2 comps and size 3 took 4 ms
Cycle complete with 3 comps and size 7 took 3 ms
Cycle complete with 4 comps and size 20 took 11 ms
Cycle complete with 5 comps and size 57 took 25 ms
Cycle complete with 6 comps and size 189 took 20 ms
Cycle complete with 7 comps and size 648 took 71 ms
Cycle complete with 8 comps and size 2088 took 261 ms
Cycle complete with 9 comps and size 5703 took 572 ms
Cycle complete with 10 comps and size 11668 took 1021 ms
Cycle complete with 11 comps and size 16094 took 1996 ms
Cycle complete with 12 comps and size 13304 took 1821 ms
Cycle complete with 13 comps and size 6677 took 761 ms
Cycle complete with 14 comps and size 2219 took 158 ms
Cycle complete with 15 comps and size 507 took 38 ms
Cycle complete with 16 comps and size 77 took 13 ms
Cycle complete with 17 comps and size 18 took 0 ms
Cycle complete with 18 comps and size 9 took 1 ms
Cycle complete with 19 comps and size 1 took 0 ms
Took 6797797437 ns
[3, 12, 48, 192, 5, 10, 80, 160, 36, 17, 136, 40, 66, 96, 40, 18, 6, 20, 24]
Will be using 24 threads
Cycle complete with 2 comps and size 3 took 8 ms
Cycle complete with 3 comps and size 7 took 5 ms
Cycle complete with 4 comps and size 20 took 12 ms
Cycle complete with 5 comps and size 59 took 20 ms
Cycle complete with 6 comps and size 208 took 33 ms
Cycle complete with 7 comps and size 807 took 173 ms
Cycle complete with 8 comps and size 3415 took 605 ms
Cycle complete with 9 comps and size 14343 took 2228 ms
Cycle complete with 10 comps and size 55986 took 17128 ms
Cycle complete with 11 comps and size 188714 took 139224 ms
Cycle complete with 12 comps and size 490251 took 945710 ms
Cycle complete with 13 comps and size 854520 took 3287401 ms
Cycle complete with 14 comps and size 914339 took 4705779 ms
Cycle complete with 15 comps and size 607161 took 2692819 ms
Cycle complete with 16 comps and size 274249 took 709728 ms
Cycle complete with 17 comps and size 94085 took 103660 ms
Cycle complete with 18 comps and size 25785 took 10027 ms
Cycle complete with 19 comps and size 5698 took 844 ms
Cycle complete with 20 comps and size 1107 took 59 ms
Cycle complete with 21 comps and size 250 took 13 ms
Cycle complete with 22 comps and size 73 took 3 ms
Cycle complete with 23 comps and size 27 took 0 ms
Cycle complete with 24 comps and size 8 took 1 ms
Cycle complete with 25 comps and size 1 took 0 ms
Took 12615521409224 ns
[3, 12, 48, 10, 80, 132, 257, 384, 5, 20, 5, 160, 136, 66, 320, 384, 72, 34, 6, 48, 24, 12, 48, 96, 192]
========================================================================
Epilogue args:
Date: Wed Apr 13 10:43:21 CEST 2016
Allocated nodes:
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
r4i2n3
Job ID: 20281753.hpc-p-svcs-10.icts.hpc.kuleuven.be
User ID: vsc31468
Group ID: vsc31468
Job Name: test20160413.pbs
Session ID: 21227
Resource List: neednodes=1:ppn=24:haswell,nodes=1:ppn=24:haswell,pmem=1gb,walltime=05:00:00
Resources Used: cput=71:00:53,energy_used=0,mem=5542500kb,vmem=21003520kb,walltime=03:30:25
Queue Name: q24h
Account String: 
-------------------------------------------------------------------------
time: 12625
nodes: 1
procs: 24
account: default_project
