.PHONY: clean All

All:
	@echo "----------Building project:[ SingleProcessor - Debug ]----------"
	@cd "SingleProcessor" && "$(MAKE)" -f  "SingleProcessor.mk"
clean:
	@echo "----------Cleaning project:[ SingleProcessor - Debug ]----------"
	@cd "SingleProcessor" && "$(MAKE)" -f  "SingleProcessor.mk" clean
