time: 1800
nodes: 2
procs: 40
account string: default_project
queue: q1h
========================================================================
Will be using 40 threads
Cycle complete with 2 comps and size 3 took 6 ms
Cycle complete with 3 comps and size 7 took 13 ms
Cycle complete with 4 comps and size 20 took 21 ms
Cycle complete with 5 comps and size 60 took 44 ms
Cycle complete with 6 comps and size 214 took 101 ms
Cycle complete with 7 comps and size 864 took 161 ms
Cycle complete with 8 comps and size 3996 took 398 ms
Cycle complete with 9 comps and size 20125 took 3592 ms
Cycle complete with 10 comps and size 105330 took 60131 ms
Cycle complete with 11 comps and size 544874 took 1265853 ms
========================================================================
Epilogue args:
Date: Thu Feb 25 16:38:18 CET 2016
Allocated nodes:
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
Job ID: 20255356.icts-p-svcs-1
User ID: vsc31468
Group ID: vsc31468
Job Name: test10_debugrun.pbs
Session ID: 11067
Resource List: neednodes=2:ppn=20,nodes=2:ppn=20,pmem=3gb,walltime=00:30:00
Resources Used: cput=09:43:01,mem=3403508kb,vmem=21948884kb,walltime=00:30:43
Queue Name: q1h
Account String: 
-------------------------------------------------------------------------
time: 1843
nodes: 2
procs: 40
account: default_project
