time: 180
nodes: 1
procs: 20
account string: default_project
queue: q1h
========================================================================
Will be using 20 threads
Cycle complete with 2 comps and size 3 took 5 ms
Cycle complete with 3 comps and size 7 took 6 ms
Cycle complete with 4 comps and size 20 took 12 ms
Cycle complete with 5 comps and size 59 took 33 ms
Cycle complete with 6 comps and size 208 took 34 ms
Cycle complete with 7 comps and size 807 took 72 ms
Cycle complete with 8 comps and size 3415 took 206 ms
Cycle complete with 9 comps and size 14343 took 1566 ms
Cycle complete with 10 comps and size 55986 took 15361 ms
Cycle complete with 11 comps and size 188722 took 147953 ms
========================================================================
Epilogue args:
Date: Thu Feb 25 10:10:26 CET 2016
Allocated nodes:
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
r4i0n9
Job ID: 20255021.icts-p-svcs-1
User ID: vsc31468
Group ID: vsc31468
Job Name: test9_debugmode.pbs
Session ID: 31417
Resource List: mem=6gb,neednodes=1:ppn=20,nodes=1:ppn=20,pmem=1gb,walltime=00:03:00
Resources Used: cput=01:03:59,mem=1223208kb,vmem=20551672kb,walltime=00:03:33
Queue Name: q1h
Account String: 
-------------------------------------------------------------------------
time: 213
nodes: 1
procs: 20
account: default_project
