time: 18000
nodes: 1
procs: 24
account string: default_project
queue: q24h
========================================================================
Will be using 24 threads
Cycle complete with 2 comps and size 3 took 3 ms
Cycle complete with 3 comps and size 4 took 1 ms
Cycle complete with 4 comps and size 2 took 1 ms
Cycle complete with 5 comps and size 1 took 1 ms
Took 19435501 ns
[3, 12, 5, 10, 6]
Will be using 24 threads
Cycle complete with 2 comps and size 3 took 3 ms
Cycle complete with 3 comps and size 6 took 1 ms
Cycle complete with 4 comps and size 11 took 1 ms
Cycle complete with 5 comps and size 10 took 2 ms
Cycle complete with 6 comps and size 7 took 2 ms
Cycle complete with 7 comps and size 6 took 1 ms
Cycle complete with 8 comps and size 4 took 1 ms
Cycle complete with 9 comps and size 1 took 1 ms
Took 24276606 ns
[3, 6, 3, 24, 10, 20, 12, 5, 3]
Will be using 24 threads
Cycle complete with 2 comps and size 3 took 3 ms
Cycle complete with 3 comps and size 7 took 2 ms
Cycle complete with 4 comps and size 17 took 4 ms
Cycle complete with 5 comps and size 36 took 8 ms
Cycle complete with 6 comps and size 53 took 16 ms
Cycle complete with 7 comps and size 53 took 13 ms
Cycle complete with 8 comps and size 44 took 4 ms
Cycle complete with 9 comps and size 23 took 1 ms
Cycle complete with 10 comps and size 8 took 1 ms
Cycle complete with 11 comps and size 4 took 1 ms
Cycle complete with 12 comps and size 1 took 1 ms
Took 70032632 ns
[3, 6, 3, 24, 48, 24, 9, 18, 10, 36, 12, 24]
Will be using 24 threads
Cycle complete with 2 comps and size 3 took 4 ms
Cycle complete with 3 comps and size 7 took 2 ms
Cycle complete with 4 comps and size 19 took 4 ms
Cycle complete with 5 comps and size 51 took 21 ms
Cycle complete with 6 comps and size 141 took 19 ms
Cycle complete with 7 comps and size 325 took 22 ms
Cycle complete with 8 comps and size 564 took 57 ms
Cycle complete with 9 comps and size 678 took 93 ms
Cycle complete with 10 comps and size 510 took 70 ms
Cycle complete with 11 comps and size 280 took 25 ms
Cycle complete with 12 comps and size 106 took 8 ms
Cycle complete with 13 comps and size 33 took 2 ms
Cycle complete with 14 comps and size 11 took 1 ms
Cycle complete with 15 comps and size 6 took 1 ms
Cycle complete with 16 comps and size 1 took 1 ms
Took 343578030 ns
[3, 6, 3, 24, 96, 20, 40, 9, 34, 68, 12, 80, 48, 24, 10, 6]
Will be using 24 threads
Cycle complete with 2 comps and size 3 took 5 ms
Cycle complete with 3 comps and size 7 took 3 ms
Cycle complete with 4 comps and size 20 took 11 ms
Cycle complete with 5 comps and size 57 took 42 ms
Cycle complete with 6 comps and size 189 took 21 ms
Cycle complete with 7 comps and size 648 took 73 ms
Cycle complete with 8 comps and size 2088 took 504 ms
Cycle complete with 9 comps and size 5703 took 1740 ms
Cycle complete with 10 comps and size 11669 took 3152 ms
Cycle complete with 11 comps and size 16093 took 4085 ms
Cycle complete with 12 comps and size 13308 took 3111 ms
Cycle complete with 13 comps and size 6679 took 1378 ms
Cycle complete with 14 comps and size 2215 took 479 ms
Cycle complete with 15 comps and size 503 took 118 ms
Cycle complete with 16 comps and size 77 took 10 ms
Cycle complete with 17 comps and size 18 took 0 ms
Cycle complete with 18 comps and size 9 took 0 ms
Cycle complete with 19 comps and size 1 took 1 ms
Took 14755053198 ns
[3, 12, 48, 192, 5, 10, 80, 160, 36, 17, 20, 136, 40, 66, 18, 6, 96, 40, 24]
Will be using 24 threads
Cycle complete with 2 comps and size 3 took 9 ms
Cycle complete with 3 comps and size 7 took 5 ms
Cycle complete with 4 comps and size 20 took 13 ms
Cycle complete with 5 comps and size 59 took 19 ms
Cycle complete with 6 comps and size 208 took 32 ms
Cycle complete with 7 comps and size 807 took 174 ms
Cycle complete with 8 comps and size 3415 took 1527 ms
Cycle complete with 9 comps and size 14343 took 6488 ms
Cycle complete with 10 comps and size 55990 took 37197 ms
Cycle complete with 11 comps and size 188719 took 347539 ms
========================================================================
Epilogue args:
Date: Tue Apr 12 16:19:39 CEST 2016
Allocated nodes:
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
r8i0n13
Job ID: 20281449.hpc-p-svcs-10.icts.hpc.kuleuven.be
User ID: vsc31468
Group ID: vsc31468
Job Name: test20160412.pbs
Session ID: 2221
Resource List: neednodes=1:ppn=24:haswell,nodes=1:ppn=24:haswell,pmem=1gb,walltime=05:00:00
Resources Used: cput=02:57:58,energy_used=0,mem=1274132kb,vmem=21003520kb,walltime=00:08:55
Queue Name: q24h
Account String: 
-------------------------------------------------------------------------
time: 535
nodes: 1
procs: 24
account: default_project
