time: 18000
nodes: 1
procs: 24
account string: default_project
queue: q24h
========================================================================
Will be using 48 threads
Cycle complete with 2 comps and size 3 took 3 ms
Cycle complete with 3 comps and size 4 took 1 ms
Cycle complete with 4 comps and size 2 took 1 ms
Cycle complete with 5 comps and size 1 took 1 ms
Took 22078607 ns
[3, 12, 5, 10, 6]
Will be using 48 threads
Cycle complete with 2 comps and size 3 took 2 ms
Cycle complete with 3 comps and size 6 took 2 ms
Cycle complete with 4 comps and size 11 took 1 ms
Cycle complete with 5 comps and size 10 took 2 ms
Cycle complete with 6 comps and size 7 took 1 ms
Cycle complete with 7 comps and size 6 took 1 ms
Cycle complete with 8 comps and size 4 took 1 ms
Cycle complete with 9 comps and size 1 took 1 ms
Took 22546748 ns
[3, 6, 3, 24, 10, 20, 12, 5, 3]
Will be using 48 threads
Cycle complete with 2 comps and size 3 took 3 ms
Cycle complete with 3 comps and size 7 took 3 ms
Cycle complete with 4 comps and size 17 took 4 ms
Cycle complete with 5 comps and size 36 took 8 ms
Cycle complete with 6 comps and size 53 took 15 ms
Cycle complete with 7 comps and size 53 took 9 ms
Cycle complete with 8 comps and size 44 took 5 ms
Cycle complete with 9 comps and size 23 took 2 ms
Cycle complete with 10 comps and size 8 took 1 ms
Cycle complete with 11 comps and size 4 took 1 ms
Cycle complete with 12 comps and size 1 took 1 ms
Took 63511352 ns
[3, 6, 3, 24, 48, 24, 9, 18, 10, 36, 12, 24]
Will be using 48 threads
Cycle complete with 2 comps and size 3 took 4 ms
Cycle complete with 3 comps and size 7 took 2 ms
Cycle complete with 4 comps and size 19 took 4 ms
Cycle complete with 5 comps and size 51 took 18 ms
Cycle complete with 6 comps and size 141 took 21 ms
Cycle complete with 7 comps and size 325 took 20 ms
Cycle complete with 8 comps and size 564 took 52 ms
Cycle complete with 9 comps and size 678 took 51 ms
Cycle complete with 10 comps and size 510 took 32 ms
Cycle complete with 11 comps and size 280 took 17 ms
Cycle complete with 12 comps and size 106 took 7 ms
Cycle complete with 13 comps and size 33 took 2 ms
Cycle complete with 14 comps and size 11 took 1 ms
Cycle complete with 15 comps and size 6 took 1 ms
Cycle complete with 16 comps and size 1 took 1 ms
Took 248042962 ns
[3, 6, 24, 96, 10, 72, 33, 3, 48, 24, 96, 10, 36, 20, 12, 96]
Will be using 48 threads
Cycle complete with 2 comps and size 3 took 5 ms
Cycle complete with 3 comps and size 7 took 4 ms
Cycle complete with 4 comps and size 20 took 12 ms
Cycle complete with 5 comps and size 57 took 25 ms
Cycle complete with 6 comps and size 189 took 23 ms
Cycle complete with 7 comps and size 648 took 70 ms
Cycle complete with 8 comps and size 2088 took 247 ms
Cycle complete with 9 comps and size 5701 took 610 ms
Cycle complete with 10 comps and size 11667 took 1150 ms
Cycle complete with 11 comps and size 16090 took 2055 ms
Cycle complete with 12 comps and size 13307 took 1993 ms
Cycle complete with 13 comps and size 6677 took 790 ms
Cycle complete with 14 comps and size 2218 took 175 ms
Cycle complete with 15 comps and size 504 took 43 ms
Cycle complete with 16 comps and size 77 took 10 ms
Cycle complete with 17 comps and size 18 took 1 ms
Cycle complete with 18 comps and size 9 took 0 ms
Cycle complete with 19 comps and size 1 took 0 ms
Took 7232507926 ns
[3, 12, 48, 192, 5, 10, 80, 160, 36, 17, 20, 136, 40, 66, 72, 96, 18, 6, 24]
Will be using 48 threads
Cycle complete with 2 comps and size 3 took 12 ms
Cycle complete with 3 comps and size 7 took 9 ms
Cycle complete with 4 comps and size 20 took 12 ms
Cycle complete with 5 comps and size 59 took 20 ms
Cycle complete with 6 comps and size 208 took 35 ms
Cycle complete with 7 comps and size 807 took 168 ms
Cycle complete with 8 comps and size 3415 took 591 ms
Cycle complete with 9 comps and size 14342 took 2307 ms
Cycle complete with 10 comps and size 55977 took 19112 ms
Cycle complete with 11 comps and size 188691 took 194187 ms
========================================================================
Epilogue args:
Date: Mon Apr 25 12:03:57 CEST 2016
Allocated nodes:
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
r4i2n5
Job ID: 20290068.hpc-p-svcs-10.icts.hpc.kuleuven.be
User ID: vsc31468
Group ID: vsc31468
Job Name: test20160425_NullJump.pbs
Session ID: 3817
Resource List: neednodes=1:ppn=24:haswell,nodes=1:ppn=24:haswell,pmem=2500mb,walltime=05:00:00
Resources Used: cput=04:48:36,energy_used=0,mem=5816024kb,vmem=23645776kb,walltime=00:12:45
Queue Name: q24h
Account String: 
-------------------------------------------------------------------------
time: 765
nodes: 1
procs: 24
account: default_project
