time: 300
nodes: 2
procs: 40
account string: default_project
queue: q1h
========================================================================
Will be using 40 threads
Cycle complete with 2 comps and size 3 took 4 ms
Cycle complete with 3 comps and size 7 took 6 ms
Cycle complete with 4 comps and size 20 took 12 ms
Cycle complete with 5 comps and size 59 took 33 ms
Cycle complete with 6 comps and size 208 took 34 ms
Cycle complete with 7 comps and size 807 took 72 ms
Cycle complete with 8 comps and size 3415 took 210 ms
Cycle complete with 9 comps and size 14342 took 1682 ms
Cycle complete with 10 comps and size 55978 took 16983 ms
Cycle complete with 11 comps and size 188709 took 161361 ms
========================================================================
Epilogue args:
Date: Tue Feb 23 16:41:40 CET 2016
Allocated nodes:
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n13
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
r5i1n14
Job ID: 20254271.icts-p-svcs-1
User ID: vsc31468
Group ID: vsc31468
Job Name: test9_debugmode.pbs
Session ID: 44891
Resource List: neednodes=2:ppn=20,nodes=2:ppn=20,pmem=1gb,walltime=00:05:00
Resources Used: cput=01:38:14,mem=2722704kb,vmem=21948884kb,walltime=00:05:11
Queue Name: q1h
Account String: 
-------------------------------------------------------------------------
time: 311
nodes: 2
procs: 40
account: default_project
